### ISSUE TITLE
Start with OpenAPI Generator 

### ISSUE THREAD

**Issue by danlooo** [Open-EO/openeo-julia-client#1]
As suggested in https://openeo.org/documentation/1.0/developers/clients/getting-started.html, one can use the [OpenAPI Generator](https://openeo.org/documentation/1.0/developers/clients/getting-started.html) to automatically create a stub client. Fortunally, they support julia. 

```bash
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
 -i https://raw.githubusercontent.com/Open-EO/openeo-api/c5a45b4647b06e313a4f099e9119bfa3cca5c6a3/openapi.yaml \
 -g julia-client \
 -o /local/openEO.jl \
 --skip-validate-spec
```

**Comment by m-mohr** [comment]
Actually, we've never created a client with those generators, the code didn't look as useful as we thought it would be. Maybe it's better with Julia, but for all other clients we created them manually as this gives more freedom and allows to follow https://openeo.org/documentation/1.0/developers/clients/library-guidelines.html

**Comment by danlooo** [comment]
Thanks for the info! I just thought it was worth the effort to give it a quick try. I came this far at branch https://github.com/Open-EO/openeo-julia-client/tree/danlooo/issue1

1. [x] create julia package with openAPI generator docker
2. [x] call simple queries to openEO backend
3. [ ] convert results to complex Julia types

```julia
using OpenEOClient
using OpenAPI

client = OpenAPI.Clients.Client("https://earthengine.openeo.org/v1.0/")
api = OpenEOClient.EODataDiscoveryApi(client)
result = OpenEOClient.list_collections(api)
```
results in 
```
ERROR: MethodError: Cannot `convert` an object of type String to an object of type TimeZones.ZonedDateTime
 [49] exec
    @ ~/.julia/packages/OpenAPI/6gzCb/src/client.jl:434 [inlined]
 [50] #list_collections#211
    @ ~/prj/openeo-julia-client/src/apis/api_EODataDiscoveryApi.jl:109 [inlined]
 [51] list_collections(_api::OpenEOClient.EODataDiscoveryApi)
    @ OpenEOClient ~/prj/openeo-julia-client/src/apis/api_EODataDiscoveryApi.jl:107
```

Simple queries that do not parse types work:
```
julia> OpenEOClient.CapabilitiesApi(client) |> OpenEOClient.conformance
({
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core"
  ]
}
, OpenAPI.Clients.ApiResponse(Downloads.Response("https", "https://earthengine.openeo.org/v1.0//conformance", 200, "HTTP/1.1 200 OK", ["date" => "Mon, 10 Jul 2023 09:02:42 GMT", "server" => "restify", "content-type" => "application/json", "content-length" => "78"])))
```

This will give no aditional value over doing manual requests with HTTP.jl
Julia is a typed language and we want to have language specific and meaningful types, e.g. DataFrame that are not part of the generic openEO API spec. Therefore, I'll do a manual implementation.
